# -*- mode: ruby -*-
# vi: set ft=ruby et sw=2 sts=-1:
Vagrant.configure('2') do |config|
  config.vm.box = 'ck/archlinux'
  config.vm.provider 'virtualbox' do |vb, override|
    vb.gui = false
    vb.memory = 4096
    vb.cpus = 2
    vb.customize ['modifyvm', :id,'--audio','coreaudio','--audioout','on','--audiocontroller','ac97']
    vb.customize ['modifyvm', :id,'--vram','128','--accelerate3d','on','--graphicscontroller','vboxsvga']
    vb.customize ['modifyvm', :id,'--clipboard','bidirectional']
  end 
  config.vm.provision 'shell', inline: 'sudo /usr/bin/pacman -S --noconfirm ansible'
  config.vm.synced_folder '../', '/vagrant'
  config.vm.provision 'ansible_local' do |ansible|
    ansible.become = true
    ansible.install = true
    ansible.playbook = 'site.yaml'
    ansible.provisioning_path = '/vagrant/ansible'
    ansible.tags = ['mainconfig','plasma']
    ansible.verbose = 'true'
  end
  #config.vm.provision 'shell', inline: 'sudo reboot'
end
