- name: Install utilities
  pacman:
      name: "{{ packages }}"
      state: latest
      update_cache: yes

- name: mlocate service
  service:
    name: updatedb.timer
    enabled: yes
    state: started
