- name: Enable services on installed system
  command: arch-chroot {{ global_mount_point}}
    systemctl enable {{ item }}
  loop:
    - sshd
    - NetworkManager
    #- rngd
    - vboxservice

- name: Create Vagrant user
  shell: arch-chroot /mnt /usr/bin/useradd --comment 'Vagrant user' --create-home --user-group vagrant

- name: Create Vagrant's .ssh
  file:
    state: directory
    path:  "{{ global_mount_point }}/home/vagrant/.ssh/"
    owner: vagrant
    group: vagrant
    mode: '0700'

- name: Copy 10_vagrant
  copy:
    src: 10_vagrant
    dest: "{{ global_mount_point }}/etc/sudoers.d/10_vagrant"
    mode: '0440'

- name: Copy Vagrant's public key
  get_url:
    url: "https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub"
    dest: "{{ global_mount_point }}/home/vagrant/.ssh/authorized_keys"
    mode: '0600'
    owner: vagrant
    group: vagrant

- name: Generate fstab
  vars:
    fstab: "{{ global_mount_point }}/etc/fstab"
  shell: |
    set -e
    set -o pipefail
    {
      if [ -f {{ fstab }} ]; then cat {{ fstab }}; fi
      genfstab -U {{ global_mount_point }} > {{ fstab }}
      cat {{ fstab }}
    } | sort | uniq -u
  register: fstab_created
  changed_when: fstab_created.stdout
