base_packages_list:
  # Arch's base packages
  - base
  - base-devel
  - linux
  - linux-firmware
  # Additional tools needed to run Ansible and get network connectivity
  # after we reboot
  - networkmanager
  - openssh
