- name: Install deepin packages
  pacman:
      name: "{{ packages }}"
      state: latest
      update_cache: yes

- name: Update lightdm.conf
  lineinfile:
      path: /etc/lightdm/lightdm.conf
      insertafter: '^[Seat:*]'
      line: 'greeter-session=lightdm-deepin-greeter'
