- name: Configure the installed system
  hosts: all
  tags: mainconfig
  roles:
    # The hostname is set once during bootstrap and once here. The idea is to
    # set it as early as possible, but if bootstrap is skipped (i.e.
    # provisioning with Vagrant) we do it again here.
    - role: hostname
      vars:
        root: ""
    - role: custom_repos
    - role: users
    - role: locale
    - role: utils

- name: Desktop environments
  hosts: all
  roles:
    # These roles must be specified in the playbook call
    - role: de_deepin
      tags: [deepin]
    - role: de_plasma
      tags: [plasma]
    - role: de_xfce4
      tags: [xfce4]

- name: Clean
  hosts: all
  tags: mainconfig
  roles:
    - role: clean
      tags: clean