- name: Remove custom repos
  import_role:
    name: custom_repos
  vars:
    state: absent
  when: global_portable_image | default(False) | bool

- name: pacman cleanup
  shell: /usr/bin/yes | sudo /usr/bin/pacman -Scc
