- name: Export proxy variables from shell profile
  template:
    src: proxy.sh.j2
    dest: /etc/profile.d/proxy.sh

- name: Pass http{,s}_proxy through sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    line: Defaults env_keep += "{{ global_proxy_env | list | join(' ') }}"
    validate: '/usr/sbin/visudo -cf %s'

- name: Set pacman's XferCommand to curl
  lineinfile:
    create: no
    path: /etc/pacman.conf
    backrefs: yes
    regexp: '^#(XferCommand = /usr/bin/curl.*)$'
    line: '\1'
